---
- name: "Install RStudio and Configure Package Manager"
  hosts: localhost
  connection: local 


  tasks:
  - name: Install R
    yum:
      name: https://cdn.rstudio.com/r/centos-8/pkgs/R-4.0.5-1-1.x86_64.rpm
      state: present
      disable_gpg_check: true

  - name: Install RStudio
    yum:
      name: https://download2.rstudio.org/server/centos7/x86_64/rstudio-server-rhel-2022.02.0-443-x86_64.rpm
      state: present
      disable_gpg_check: true

  - name: R symlinks
    file:
      path: "/usr/local/bin/R"
      src: "/opt/R/4.0.5/bin/R"
      state: link

  - name: Create RStudio etc Directory
    file:
      path: /opt/R/4.0.5/lib/R/etc/
      state: directory
      
  - name: Create Empty RProfile
    file:
      path: /opt/R/4.0.5/lib/R/etc/Rprofile.site
      state: touch

  - name: Configure RStudio Repos
    lineinfile:
      path: /opt/R/4.0.5/lib/R/etc/Rprofile.site
      regexp: "options"
      line: 'options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/centos8/latest"))'




